### ISSUE TITLE
MRTK Eye Gaze Provider broken after tracking lost

### ISSUE THREAD

**Issue by JYBA1** [microsoft/MixedReality-WorldLockingTools-Unity#102]
We are using a couple of applications taking advantage of the HoloLens 2 eye gazing. We noticed that the eye gaze provider would sometimes stop correctly recording where the eyes were looking. 
We found two issues:
The first is around the World Locking Context Auto Load feature. It seemed that on subsequent runs of the app, the eye gazing wouldn't function correctly.
The second was that after losing tracking and relocating, the eye tracking would never recover and would be misaligned.

We tracked the problem down to the way MRTK gets the position and direction of the latest eye gaze in it's GazeProvider. We have created our own GazeProvider that takes these values and converts them from Spongy to Frozen space. So far this appears to have fixed this issue.

**Comment by fast-slow-still** [comment]
Hi @JYBA1 , great find. Have you submitted an [issue to MRTK](https://github.com/microsoft/MixedRealityToolkit-Unity/issues)? If you have, could you add a link here? I'd like to follow through and see that a fix gets in.

Issues occasionally pop up in the MRTK code where the Playspace transform isn't properly factored in. This sounds like such an issue. Do you have a fix you could share, if not for merging in then at least to cut down the time to find and resolve the issue?

Thanks!

**Comment by vbandi** [comment]
We've also ran into the same issue, and would appreciate a fix.
