### ISSUE TITLE
Legacy XR removed in Unity 2020.2

### ISSUE THREAD

**Issue by camnewnham** [microsoft/MixedReality-WorldLockingTools-Unity#114]
Importing WLT into Unity 2020.2 won't compile due to the removal of the Unity.XR.WSA.Persistence namespace (WorldAnchor and WorldAnchorStore removed).

Removing the problematic classes/references results in WLT working as expected. 

What is an appropriate way to reference this repo for Unity 2020.2+ (branch/fork/PR)?

Cheers

**Comment by fast-slow-still** [comment]
I'm glad you brought this up. I had been intending to get to Unity 2020 in the next week or two, but this gave me an excuse to take a break from something I didn't want to be doing anyway, and have a look ahead. Thanks!

**Comment by folocam** [comment]
Does persistence (Save/Load) work with the XRSDK? My understanding was that with the removal of WorldAnchors and the WorldAnchorStore this feature would be defunct - is that correct?

In our case we are using QR alignment and hence have this feature turned off (since the OS remembers QR position across sessions, however this doesn't persist across restarts).

**Comment by camnewnham** [comment]
Does persistence (Save/Load) work with the XRSDK? My understanding was that with the removal of WorldAnchors and the WorldAnchorStore this feature would be defunct - is that correct?

In our case we are using QR alignment and hence have this feature turned off (since the OS remembers QR position across sessions, however this doesn't persist across restarts).

**Comment by fast-slow-still** [comment]
You are correct that persistence isn't implemented in WLT for the XRSDK framework. Calls to Save/Load become no-ops unless the platform supports persistence. The only platform with persistence implemented in WLT currently is Legacy WMR HoloLens.

My understanding of the roadmap (don't quote me on this, there's a bit of guesswork) is that the different platforms (e.g. iOS, HoloLens) will surface persistence capabilities as extensions. Once they do, then WLT will use platform specific implementations around those. I certainly expect HoloLens, I think iOS is likely, but so far Android doesn't appear to be planning to surface wide level anchor persistence.

Again, all of that is speculative and subject to change as Unity's XRSDK support expands.

**Comment by davide-bergamini-fitstic-edu** [comment]
Hi, AnchorStore access is supported starting with Windows XR Plugin > 5.1 (28-10-2020)
- Add official API for accessing the Microsoft SpatialAnchorStore through the new XRAnchorStore class.

https://docs.unity3d.com/Packages/com.unity.xr.windowsmr@5.2/api/UnityEngine.XR.WindowsMR.XRAnchorSubsystemExtensions.html
https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-supported-features#anchor-persistence-and-the-xranchorstore

I wanted to start integrate it myself in WLT (but my code quality isn't going to be very good) 
Can you tell me if you're going to do it yourself, maybe in a couple of weeks?

Thanks you very much
Davide Bergamini

**Comment by fast-slow-still** [comment]
Hi Davide (@davide-bergamini-fitstic-edu), yes, I've been following that closely. I don't see too much complication there, but as you say, it is important to fit it in cleanly. It is already near the top of my to-do list (I have to finish up with a packaging issue first), so I would say that having it out in the next couple of weeks is a safe estimate.

Let me know if scheduling becomes urgent for you and I will do my best to accommodate. But if you do, please file it as a new issue. Thanks!

**Comment by davide-bergamini-fitstic-edu** [comment]
Thanks a lot!
