### ISSUE TITLE
Release 1.2.4 breaks spatial mesh on XR SDK

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedReality-WorldLockingTools-Unity#130]
This is a regression from upgrading to MRTK v2.5.4. Same fix needs to be applied.

Fix will be in MRTK from v2.6.0.

**Comment by zantiu** [comment]
So still manually apply this fix,  right?

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8929/files

**Comment by fast-slow-still** [comment]
Yes. Also, it will be included again in the modified MRTK v2.5.4 packaged with Examples in next WLT release 1.2.5 in the next couple of days. It just slipped by me when I upgraded to v2.5.4. Apologies.

**Comment by fast-slow-still** [comment]
This is fixed in the linked PR, and in release v1.2.6
