### ISSUE TITLE
WLT + MRTK + Holographic Remoting in Unity - No Anchor Subsystems error.

### ISSUE THREAD

**Issue by jpapon** [microsoft/MixedReality-WorldLockingTools-Unity#162]
So I've been trying for a couple days now to get WLT working with my Hololens 2, Holographic Remoting (in the Unity editor) MRTK and Unity 2020.3 ( I also tried 2019.4 without success). I can get the Holographic Remoting working without problem, but WLT fails to load any anchor manager, and so doesn't seem to do anything. Exact debug messages I receive are at the bottom here.

Exact steps to reproduce are below - am I doing something wrong, or does this just not work at the moment?
The procedure used below is for Windows XR Plugin, but I've also tried using OpenXR without any success.

Following the directions: 
Project/MRTK Setup: https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/tutorials/mr-learning-base-02?tabs=winxr  
WLT Setup: https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/InitialSetup.html#adding-world-locking-tools-to-a-unity-scene

Using the Windows XR Plugin
1. Install Unity 2020.3.4f1 with UWP and IL2CPP and create a new Project
2. Switch to UWP in Build Settings 
3. Import TextMesh Pro Essential Resources
4. Using Mixed Reality Feature Tool, add the following to the project:
    - Mixed Reality Toolkit Extensions 2.6.1
    - Mixed Reality Toolkit Foundation 2.6.1
    - Mixed Reality Toolkit Standard Assets 2.6.1
    - WLT Core 1.3.5
5. Apply MRTK Default Settings
6. Install XR Plugin Management
7. For both standalone and UWP, Check Windows Mixed Reality and Initialize XR on Startup
8. Under Windows Mixed Reality, check Holographic Remoting for both Standalone and UWP.
9. Under Player->Publishing Settings -> Capabilities, Add Webcam and InternetClientServer
10. Window -> XR -> Windows XR Plugin Remoting, Set Remote to Device, Set IP shown on Hololens Remoting App.
11. Mixed Reality Toolkit -> Add to Scene and Configure.
12. On the MRTK Gameobject, Switch to DefaultXRSDKConfigurationProfile 

Now if I hit play, I can see my Unity scene in the Hololens 2, so far so good.

Try to add World Locking Tools:
1. Mixed Reality Toolkit -> Utilities -> World Locking Tools -> Configure Scene
2. World Locking Manager Anchor Management is set to "XRSDK".

When I hit play, I get the following messages (deleted the traces for brevity)
Null: Creating AnchorManagerNull
Select XRSDK anchor manager.
Creating new anchormanager, but have old one. Reseting it before replacing.
Trying to create XR anchor manager
Found 0 anchor subsystems.
Found no anchor subsystem running, will try starting one.
ERROR: Found 0 active anchor subsystems, expected exactly one.
Failed to create requested XR SDK anchor manager!
Failure creating useful anchor manager of any type. Creating null manager
Null: Creating AnchorManagerNull

If I switch to WSA for Anchor Management, I get something similar just with WSA instead of XR.

Also, don't know if this is related, but I'm getting this error message too:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\...\Library\PackageCache\com.microsoft.mixedreality.worldlockingtools@1b0a49d9b4b5-1619025180880\Packages\Microsoft.MixedReality.Unity.FrozenWorld.Engine.1.1.0\lib\unity\iOS-ARM64\FrozenWorldPlugin.framework'.

I don't know why it's looking for an iOS-ARM64 dll though....

Anyways. Any help would be appreciated.

**Comment by fast-slow-still** [comment]
Hi Jeremie.

Starting from the easy bit, that last error message is harmless. When installed from MR Feature Tool, WLT paths get extended with a lot of boilerplate, as you can see in the path you cut and paste. They then exceed the Windows path length limit. The current workaround is to install to a shorter path. See issue #161 for more details.

On your main issue, have you tried deploying and running directly on device? I haven't seen the issue that you are describing, but I never use Holographic Remoting. It would be helpful to know if the problem is specific to Holographic Remoting, or more general to your setup.

It is quite possible that Holographic Remoting doesn't currently support device anchor creation, although I know that in the past it did. Please let me know if you can run directly on device, so I'll be able to dig into this further. Thanks!

**Comment by jpapon** [comment]
Hi Mark! 

I'm not able to deploy to the device at the moment for my main project as I have some dependencies that don't run on ARM64. Though I will try to deploy a test project soon to see if WLT works.

If I wanted to go back to using WSA, what is the recommended Unity version? Is 2019.4 okay?
If I remember right, I believe a test I ran on 2019.4 did work with remoting at some point. I've tried so many different combinations of the different SDKs and Unity versions at this point that it's difficult to remember =)

**Comment by fast-slow-still** [comment]
That's correct, WSA is deprecated in U2019, and gone in U2020. I test extensively with Unity 2019.4 (all incremental versions, latest should be fine). I *believe* at least one of my customers was using Remoting with Unity2019/WSA. I'll see if I can confirm that.

It would not surprise me if Holographic Remoting of anchors doesn't currently work in U2020/XRSDK. It would surprise me very much if it already works in OpenXR. I have some contacts on the XRSDK team, I'll reach out and see if I can get a clarification on whether Holographic Remoting of anchors is expected to work there.

Note that when deployed to device, WLT is tested and expected to work on U2018, any U2019, and through U2020.3.

I'm going to leave this issue open. I hope you'll have a chance to add updates as you gather further information. Thanks for your contributions so far, your comments are very valuable!

**Comment by jpapon** [comment]
FYI, WLT worked without without issue in 2019.4 with Holographic Remoting and WSA Anchor Subsystem.
I will just use this for now.

**Comment by fast-slow-still** [comment]
Great feedback, thanks! I'll try to follow up with the Windows XR SDK team.

**Comment by dfields-msft** [comment]
FYI #211 may fix at least part of this. It's been working well for me locally, modulo a few benign issues during disconnection.
