### ISSUE TITLE
Implement local persistence for ARFoundation

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedReality-WorldLockingTools-Unity#190]
I don't know if it's (currently) possible, but it might be useful to implement local anchor (and SpacePin) persistence for AR Foundation. Using XR SDK, local persistence is currently implemented independently via the OpenXR and WindowsMRXR Plugin extensions. 

If there is a similar extension for AR Foundation's ARAnchorManager (I haven't looked into this yet, so there might or might not be), then it could be implemented into the AnchorManagerARF/SpongyAnchorARF pipelines.

Note that the only current use for the ARFoundation path is when using ASA, and ASA kind of makes the local persistence redundant.

**Comment by zantiu** [comment]
The problem with ASA is that it cannot be applied to all use cases. For example we work in industrial plants that tightly control which applications have internet access. Every new application first needs to go through an approval that could take weeks or even months. For existing use cases the implementation teams have a good feeling of what can be allowed, but for AR applications the incertitude of this approval can be a blocking point for even considering a first pilot. Especially considering the Hololens is a device full of camera's that could capture sensitive production processes.

One solution could be to have ASA on an edge server, but I doubt this kind of solution is near, or will even ever be considered.

So it's probably important to have local anchor persistence, at least as a fall-back back or initial adaption option.

And the bad news is that it's probably not possible through AR Foundation at this moment looking at the latest docs:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/manual/anchor-manager.html
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.ARAnchorManager.html
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.2/api/UnityEngine.XR.ARFoundation.ARAnchor.html

**Comment by fast-slow-still** [comment]
@zantiu many thanks for your thoughts, as well as those links. I will bring up your concerns with colleagues involved in steering AR Foundation. They are always interested in hearing about real world industry constraints such as you describe, and I think you present a very clear and strong case.

In the meantime, I hope that the local persistence of anchors and space pins WLT provides is sufficient for your needs, and that when the time comes, the migration path to using ASA for sharing and persistence is smooth. Best wishes!
