### ISSUE TITLE
WLT not recognizing previously mapped out area

### ISSUE THREAD

**Issue by ShayneRC** [microsoft/MixedReality-WorldLockingTools-Unity#199]
We recently upgraded Unity (2020.3.13), MRTK (2.7.2) and the WLT (1.4.2). After the upgrade we noticed that the WLT were working correctly but it wasn't re-aligning to previously mapped out areas like it was before. 

Examples:

**Previous version**
- Start the app in Area1.
- Walk around with pins (AnchorGraphVisual) showing and linking.
- Cover the cameras to simulate tracking loss and walk to a new area; Area2.
- A new pin will be below you and will start linking to any new ones created.
- Once you walk back to Area1 with the cameras not covered, it would link the pins from Area2 to the ones in Area1 and place the origin back to the first pin. Which would re-align our model back to it's starting point.

**New version**
- Start the app in Area1.
- Walk around with pins (AnchorGraphVisual) showing and linking.
- Cover the cameras to simulate tracking loss and walk to a new area; Area2.
- It moves all the currently created pins from Area1 now into Area2 including the origin.
- Once you walk back to Area1 with the cameras not covered, it just keeps creating new pins linking back to the ones in Area2. 

Let me know if I can give any more information. I will attach a screenshot of the pins I'm talking about.
![20210905_215050_HoloLens](https://user-images.githubusercontent.com/54519937/132163230-dc2bdde5-8fda-4353-8ca6-87bda20bde16.jpg)

**Comment by fast-slow-still** [comment]
Hi Shayne, thanks for the great write-up! 

A quick question, can you describe your platform support? In particular, in World Locking Context / Anchor Management, what Anchor Subsystem do you have selected?
![image](https://user-images.githubusercontent.com/37700878/132189234-68bb266c-e5ec-4107-b879-aabfb291ab25.png)

Also, in Unity's XR Plugin Management, what Plugin Provider do you have? 
![image](https://user-images.githubusercontent.com/37700878/132188990-dcb1af3e-2e73-4978-b651-2a85b2efd374.png)

**Comment by ShayneRC** [comment]
Hi Mark, thanks for the quick reply.

The Anchor Subsystem is set to the **Use Defaults** - WSA.

The XR plugin provider being used is the Windows Mixed Reality with these settings:

**Build Settings**
- Use Primary Window - YES
- Holographic Remoting - NO

**Runtime Settings**
- Depth Buffer Format - Depth Buffer 16 Bit
- Shared Depth Buffer - NO

**Comment by peterneil-bimholoview** [comment]
Just to add to Shayne's comment. Because we want to use Planar LSR for ARR we have to sue Windows Mixed Reality as opposed to Open XR.

**Comment by fast-slow-still** [comment]
Okay, that's grand. I think you just need to change your Anchor Subsystem from WSA (that's the old legacy VR, deprecated in U2019 and gone in U2020), to XRSDK. You can either do this manually, on the World Locking Context, or run the Mixed Reality / World Locking Tools / Configure scene script from the Unity toolbar.

![image](https://user-images.githubusercontent.com/37700878/132317643-031b31fa-4491-4d9f-a138-d3668581825a.png)

Give that a try and let me know if it's not working as expected. Thanks!

**Comment by ShayneRC** [comment]
That has fixed it perfectly thanks!
