### ISSUE TITLE
Add ability to set Adjustment Frame to Subtree

### ISSUE THREAD

**Issue by srinjoym** [microsoft/MixedReality-WorldLockingTools-Unity#201]
We are trying to use the subtree functionality of WLT in our app. We would like to avoid changing the camera hierarchy since we use ASA in other flows of the app. Ideally, we would like to set the adjustment frame to the subtree root itself.

**Comment by fast-slow-still** [comment]
I would comment that ASA and WLT work well together, complementing each other's abilities. WLT provides local stability and control over coordinate alignment, whereas ASA provides cloud based shareable reference points (anchors).

See [the documentation here](https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/WLT_ASA.html), and the sample included with WLT.
