### ISSUE TITLE
[Feature] Optionally Disable Logging

### ISSUE THREAD

**Issue by Waffle1434** [microsoft/MixedReality-WorldLockingTools-Unity#205]
While great for debugging WLT, logging clutters the console and makes debugging personal projects more of a hassle.
It would be great if on a component, there was a boolean toggle for console logging.

In addition, if a component logs a message, I would highly suggest passing the gameobject so it highlights it in hierarchy when the message is clicked.
```CS
if (logging) Debug.Log($"Extracted pose from transform on {name}", gameObject);
// Instead of: Debug.Log($"Extracted pose from transform on {name}");
```

**Comment by fast-slow-still** [comment]
As a move in that direction, I made a couple of changes:

1. All WLT logging not directly related to startup is disabled by default.
2. All WLT logging can be suppressed with a global define WLT_DISABLE_LOGGING, which can be globally applied in Plater Settings / Other Settings / Scripting Define Symbols.
3. Full verbose mode can be achieved by defining WLT_EXTRA_LOGGING and WLT_LOG_SETUP.
4. Note that WLT_DISABLE_LOGGING overrides other logging.

I also moved from using #if's to using ConditionalAttributes, which reduces the cost of unused logging to zero (no string allocations, no string interpolation, etc).

See release v1.5.1 for all this.

There is obviously more refinement to be done, but I think this first pass on refactoring WLT's logging will address a lot of the more pressing problems.

Thanks again for the push in this direction!

**Comment by FreakTheMighty** [comment]
@fast-slow-still is there a way to disable logging in the editor? I've got this setup in project settings, but I still have a huge number of WLT logs.
![image](https://user-images.githubusercontent.com/247092/145247453-0cbf0f51-0c76-4f13-a078-12c115912f20.png)

**Comment by fast-slow-still** [comment]
Can you provide a sample of some of the logged messages? I might have missed some. When I enable that, I get zero messages from WLT.

Also, it would be great if you could file this as a new Open issue. Thanks!
