### ISSUE TITLE
Local only world locking not working with AlignSubtree

### ISSUE THREAD

**Issue by pjaydev** [microsoft/MixedReality-WorldLockingTools-Unity#207]
Hello,

I would really love using the **Local only world locking** ability in my project, which was added in the most recent 1.5.0 WLT release, on HoloLens 2 in combination with MRTK and OpenXR.

For testing this feature, I prepared a basic Unity scene. Since I do not want the camera to be moved by WLT, but only the subtree, I attached the *AlignSubtree* to an *AdjustedSpace* GameObject, placed some test objects as children and turned off the *Apply Adjustment* setting in the *World Locking Context*. The following screenshot shows how the scene is configured:

![SceneConfig](https://user-images.githubusercontent.com/34743592/134673353-f1207189-23d9-4e1e-830e-020fac850ebe.PNG)

This is the AlignSubtree configuration:

![AlignSubtreeConfig](https://user-images.githubusercontent.com/34743592/134673361-e0a2bdcd-356f-4eea-8768-f10f5307399c.png)

The SDK setup is as follows:
	 - Unity 2020.3.13
	 - OpenXR framework set as XR provider
	 - MRTK v2.7.2 with MRTK OpenXR Plug-In v1.0.3
	 - Using ARFoundation as anchor subsystem

When starting a clean session, after moving around for a bit, both the adjusted space and the graph start to fly away slowly. You can see this behaviour from minute 0:22 in the following demo video:

https://www.youtube.com/watch?v=I8V3Ni8-5t8

From this moment on, WLT periodically creates new anchors, but obivously has problems with fitting them into the graph appropriately, as you can see from minute 0:33 on. A lot of yellow anchors are being created on nearly the same spot.

When the app is launched a second time and the recent session gets restored, the created graph appears on totally random positions. In this video you can see how it gets stuck in the ceiling after first spinning around for some time:

https://www.youtube.com/watch?v=_QpaHZ5hdDQ

Note that the blue and red edges between the anchors in the *AnchorGraphVisual* are not visible in the recorded videos, but on the HoloLens I could actually see them. 

If this behavior is due to a misconfiguration on my part, I'd be very happy for any suggestions.

Thanks!

**Comment by fast-slow-still** [comment]
Thanks for all the details, that's very helpful! I'll try to reproduce your setup. My suspicion is that there is a minor inconsistency in the AR Foundation anchor subsystem. I'll let you know what I find. 

Thanks again for the detailed write-up, your effort is very much appreciated!

**Comment by fast-slow-still** [comment]
I've managed to isolate and fix the problem, it is indeed specific to the AR Foundation anchor subsystem, which unfortunately gets less attention than the other flavors. I have v1.5.1 with the fix currently in test, hopefully, if no further issues are found, it will be released Monday Sep 27, 2021.

Many thanks again for the excellent bug report!

**Comment by pjaydev** [comment]
Thanks to you for the very quick response and your excellent work on the WLT framework.

I'm looking forward to the fix on Monday!

**Comment by fast-slow-still** [comment]
Okay, release v1.5.1 is out at all the usual channels, github code, github releases, and MR Feature Tool.

Give it a try, and please let me know if it doesn't address all your issues. 

Thanks again for the excellent write-up!

**Comment by pjaydev** [comment]
Thanks a lot for the update! 

I'm afraid I won't be able to test the fix before next Friday or even Monday, but I will let you know the result as soon as possible.

**Comment by fast-slow-still** [comment]
Awesome, no rush, I will appreciate you reporting back. I'll leave this open until then. Thanks!

**Comment by pjaydev** [comment]
I could test the new release today and everything works as expected now.

Thanks again for the quick reaction!

**Comment by fast-slow-still** [comment]
Many thanks for reporting back!
