### ISSUE TITLE
[ISV] Alignment Subtree becomes misaligned due to incorrect space pin height

### ISSUE THREAD

**Issue by srinjoym** [microsoft/MixedReality-WorldLockingTools-Unity#232]
We are running into an intermittent issue with the subtree in our app becoming misaligned after lost/regained tracking cycles. We are using multiple `SpacePinOrientable`s to align a large model to multiple QR codes

**Comment by srinjoym** [comment]
We repro'd this issue again today - was not related to tracking loss. It seems like the space pin height is somehow jumping up to the wrong place. More data included privately

**Comment by fast-slow-still** [comment]
Not enough info here to repro or even investigate. Closing.
