### ISSUE TITLE
Object offset after tracking loss

### ISSUE THREAD

**Issue by NLR-L** [microsoft/MixedReality-WorldLockingTools-Unity#234]
Sometimes after having experienced a tracking loss, all my objects that were lined up with the real world before have an offset of 0.5-10 cm.  For most of our use cases that would be fine, when anchors are used to place objects for interaction the user wont remember it that accurately anyways, but we try to match the object position to a point on the mesh.

WLT seems to think that it correctly lined up. It can be hard to notice, but at the start the objects are perfectly lined up with the real world and after the "tracking lost" they've drifted.

I think it's the same issue is #232, except that I don't even use the subtree. 

Edit:

I'm having troubles pinning down what's going wrong, because sometimes it recovers just fine and other times it's messed up by a small offset.

The spatial mapping itself looks fine, but if I make a copy of it, the copy will have a small offset after some "tracking losts", while the actual mesh still has the good position.  This might be because the mesh gets an update after tracking lost from the mesh observer.

**Comment by fast-slow-still** [comment]
Hi @NLR-L , could you clarify this a little? What kind of objects have drifted? Are these HoloGrams, or the spatial mapping mesh? 
Thanks!

**Comment by NLR-L** [comment]
The objects that have drifted are the holograms.  I tried to explain that if I create a copy of the spatial mapping mesh, that the copy will be at a slightly different position than the actual spatial mesh after the tracking was lost. In this case it was easy to verify the offset, because I could compare the two meshes.

I will try to create pictures of the problem, but I'm really busy at the moment, so that might take a while.

**Comment by fast-slow-still** [comment]
Fantastic! Thanks for the update!
