### ISSUE TITLE
[ISV] FWE diagnostics continue after toggling off

### ISSUE THREAD

**Issue by fast-slow-still** [microsoft/MixedReality-WorldLockingTools-Unity#235]
With application running, turn diagnostics on from script.

Logging starts fine.

Turn diagnostics off from script. Logging seems to continue.

**Comment by srinjoym** [comment]
Method we're using to disable/enable logging:
```
    public void SetWLTLogging(bool enabled)
    {
        var wltMgr = WorldLockingManager.GetInstance();

        DiagnosticsSettings diag = new DiagnosticsSettings()
        {
            UseDefaults = !enabled,
            Enabled = true,
            StorageSubdirectory = AppServices.AlignmentValidationService.DiagnosticsPath,
            StorageFileTemplate = "FrozenWorld-[Machine]-[Timestamp].hkfw",
            MaxKilobytesPerFile = 2048,
            MaxNumberOfFiles = 64
        };

        wltMgr.DiagnosticsSettings = diag;

        if (!enabled)
        {
            // Upload hkfw files to storage
            AppServices.AlignmentValidationService.UploadDiagnostics();
        }
    }
```
Repro steps (on HL2):

1. We're starting with logging turned off on the World Locking Context:
![image](https://user-images.githubusercontent.com/7866060/144688689-7467c012-c1c8-4f36-b04c-47209f63d2d0.png)
2. Use method above to enable logging
3. WLT starts logging to diagnostics folder (keep running for at least a minute)
4. Use method above to disable logging
5. Bug: WLT keeps writing .hkfw files to diagnostics folder
6. Bug: WLT keeps writing .hkfw files even after repeated enable/disables using method above

If this doesn't repro I would recommend keeping it enabled for longer and enabling/disabling a few times

**Comment by fast-slow-still** [comment]
Hi Srinjoy, please try the following. Note the slight change to the diagnostics settings UseDefaults and Enabled:

```csharp
        public void SetWLTLogging(bool enabled)
        {
            var wltMgr = WorldLockingManager.GetInstance();

            DiagnosticsSettings diag = new DiagnosticsSettings()
            {
                UseDefaults = false,
                Enabled = enabled,
                StorageSubdirectory = AppServices.AlignmentValidationService.DiagnosticsPath,
                StorageFileTemplate = "FrozenWorld-[Machine]-[Timestamp].hkfw",
                MaxKilobytesPerFile = 2048,
                MaxNumberOfFiles = 64
            };

            wltMgr.DiagnosticsSettings = diag;

            if (!enabled)
            {
                // Upload hkfw files to storage
                AppServices.AlignmentValidationService.UploadDiagnostics();
            }
        }
```

**Comment by srinjoym** [comment]
Sorry for the delay on the response, finally got a chance to test this solution today and it seems to have fixed it! Great catch on the incorrect `enabled` state.

It looks like setting `UseDefaults` to true doesn't disable logging. I'm opening the issue again as this behavior still seems like a bug to me. If it's by design, it would be great to add some docs on how to enable/disable diagnostics with a note on this

**Comment by fast-slow-still** [comment]
The default is to disable logging. Setting UseDefaults to true disables logging. If you click on UseDefaults in the Unity Inspector, you can see this.

**Comment by fast-slow-still** [comment]
By the way, this is already documented. The Diagnostics settings are documented here:
https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/WorldLockingContext.html#diagnostics-settings

And there is a special section explaining the UseDefaults here:
https://microsoft.github.io/MixedReality-WorldLockingTools-Unity/DocGen/Documentation/HowTos/WorldLockingContext.html#default-settings

**Comment by srinjoym** [comment]
Ah got it, thanks for the pointer on the docs! It seems a bit confusing that the defaults can change to the current value, but I think that's a separate discussion. Should be good to keep this issue closed
