### ISSUE TITLE
Can't disable logging in editor

### ISSUE THREAD

**Issue by FreakTheMighty** [microsoft/MixedReality-WorldLockingTools-Unity#246]
Based on https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/issues/205 I should be able to disable logging. But for some reason I can't get it work in editor. I've updated project settings accordingly.

![image](https://user-images.githubusercontent.com/247092/145247453-0cbf0f51-0c76-4f13-a078-12c115912f20.png)

But I still see many logs.

![image](https://user-images.githubusercontent.com/247092/145251101-49fe946a-98f2-4b51-9415-bedd4b1a1250.png)

I can see that the logs do seem like they should be removed

```c#
  [System.Diagnostics.Conditional("WLT_LOG_SETUP")]
  protected static void DebugLogSetup(string message)
  {
      Debug.Log(message);
  }
```
But somehow it doesn't seem like the `#undef WLT_LOG_SETUP` is working...

**Comment by fast-slow-still** [comment]
Can you tell me what Anchor Manager Subsystem you are using? (ARFoundation, XRSDK, WSA)
And what your version of Unity is?

Thanks!

**Comment by fast-slow-still** [comment]
By the way, do you have the "Null Subsystem in Editor" boxed checked in the Anchor Management Settings? You should, because that error is telling you that it is failing to start the XR system (because it's in the editor), and is going to try again. The "Null Subsystem in Editor" option tells it to use a placeholder anchor system, because the real one will fail.

**Comment by fast-slow-still** [comment]
I just verified it is working as expected. Two gotchas to check for:
1. Did you hit "Apply" when you added the WLT_DISABLE_LOGGING define?
2. Did you add the define to the settings for the current build target?

**Comment by AMollis** [comment]
Mark, the bug appears to be in AnchorManagerXR.cs.   It's missing this **_line_**.  It's missing undef'ing WLT_LOG_SETUP when WLT_DISABLE_LOGGING is defined

```
#if WLT_DISABLE_LOGGING
#undef WLT_EXTRA_LOGGING
_**#undef WLT_LOG_SETUP**_   
#endif // WLT_DISABLE_LOGGING
```

Others are likely not hitting this because they are using a different AnchorManager; for example AnchorManagerARF.cs.

**Comment by fast-slow-still** [comment]
@AMollis , it shouldn't matter whether it's defined in AnchorManagerXR.cs, it only matters whether it is defined in the file that uses it, in this case AnchorManager.cs, where the function DebugLogSetup() is defined.

Again, I tried this with the same configuration, and it behaved as expectedly. The two gotchas I mentioned are very easy to miss (I missed one of them the first time testing this).

**Comment by AMollis** [comment]
FWIW the bug went away once I added this line.  I suspect it’s some quirk with how script is compiled in editor.  Note, the project we repro’ed with had the “Anchor Subsystem” set to XRSDK

**Comment by fast-slow-still** [comment]
Yes, I was testing with Anchor Subsystem==XRSDK. 

As you say, it might be a bug in Unity. As I'm sure you have noticed, WLT_LOG_SETUP isn't even used in AnchorManagerXR.cs, so whether it is defined in that file or not should have no consequence. I would suggest you file a bug report with Unity.
