### ISSUE TITLE
Allow the ability to save Anchors to a path similar to Space Pins

### ISSUE THREAD

**Issue by MaxwellSpectar** [microsoft/MixedReality-WorldLockingTools-Unity#258]
Currently only Space Pins are allowed to be saved to a Path via the AlignSubtree class that exposes the SaveFileName property. It would be useful to have the AnchorManager expose a similar property so there can be a direct correlation to what Space pins are linked to generated anchors. @srinjoym @fast-slow-still

**Comment by MaxwellSpectar** [comment]
Sure thing @FreakTheMighty. Basically we have these zones that are really just a 3D model that corresponds to the space you're in. A particular real life area might have more than one zone depending on how big and diverse it is. Meaning that in the same real world space we can have different space pins and anchors generated depending on the zone that was selected, therefore it would be useful if we could regenerate those particular anchors like how we can with the Space pins. Hope that is clear enough, if not I can give more examples.

**Comment by fast-slow-still** [comment]
This feature is done and tested, and will be in release 1.5.8, which will be as soon as I get it through test (this week or next, depending on how test goes).

**Comment by fast-slow-still** [comment]
See WorldLockingManager.FrozenWorldFileName, in release 1.5.8 or later, or PR #260
