### ISSUE TITLE
Minor index error in SpacePinBinder AddSpacePin

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedReality-WorldLockingTools-Unity#277]
In the code in SpacePinBinder file, when you attempt to add a pin at runtime it will re-add the first item in the index:

    public bool AddSpacePin(SpacePinQrAsa spacePin)
    {
        // mafish - make sure it's not already in there.
        int idx = FindSpacePin(spacePin);
        if (idx <= 0)
        {
            SpacePins.Add(spacePin);

But, in FindSpacePin, the first item in the list returns an index of 0

    /// <returns>Index in the list if found, else -1.</returns>

Which falls through the if statement and then gets added again to the list

    if (idx <= 0)

I think this should just be <, rather than <=:

    if (idx < 0)

**Comment by fast-slow-still** [comment]
@genereddick, yes, you're right, that's a type-o, and if `(idx <= 0)` should be `if (idx < 0)`.

Thanks for reporting it!

**Comment by fast-slow-still** [comment]
Fixed with #279 

Also fixed in the sibling Samples repo:
https://github.com/microsoft/MixedReality-WorldLockingTools-Samples/pull/83

Many thanks again for pointing this out!
