### ISSUE TITLE
Setting world origin to Pin

### ISSUE THREAD

**Issue by genereddick** [microsoft/MixedReality-WorldLockingTools-Unity#283]
If I want multiple devices to have the same origin pose -- so that every device will both see an asset in the same location but the actual asset transform pose values will be identical on each device -- does this require anything more than setting a pin with a global pose of Pose.identity and whatever virtual pose each device detects?

**Comment by fast-slow-still** [comment]
Yes, you could do that with a single pin (per device). There would be limits on the quality of alignment, as discussed [here](https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/issues/281#issuecomment-1102582622) and [here](https://docs.microsoft.com/en-us/mixed-reality/world-locking-tools/documentation/concepts/advanced/spacepins#addressing-the-scale-error).

To be clear, if I understand what you are suggesting, you would have a SpacePin component on an object in your scene at the global origin (position=(0,0,0), rotation=(0,0,0,1)). You would somehow establish what pose (frozenPose) the device currently has at the physical location where you want the shared global origin to be. 

Then, with your SpacePin's global pose at identity, you would `spacePin.SetFrozenPose(frozenPose)`, where `frozenPose` is the pose determined per device above.

That might be all the alignment accuracy your application needs. As discussed in the above links, you can improve accuracy from there with additional pins.
