### ISSUE TITLE
WLT + ASA not working

### ISSUE THREAD

**Issue by Ahim13** [microsoft/MixedReality-WorldLockingTools-Unity#286]
WLT is implemented in our project and is working fine, and now we wanted to implement ASA as well.
After following the guides, the build is successful, but on the Hololens 2 the following issues are present:

1. Grabbing the spheres in the scene with the Sofa they just snap back to their original place and seemingly they don't do much (only print new values to the console)
2. When pressing Publish it starts the process, but immediately gives back an error: "_Could not obtain the ARAcnhor.Nativeptr_". (- probably because of this the loading / search does not find any matching anchors from the server.)

We tried it in our project then tried the sample project (https://github.com/microsoft/MixedReality-WorldLockingTools-Samples/tree/master/Advanced).

The sample project had the same result (also worth mentioning that the sample project did not work out of the box, but we had to add the ASA core and ASA windows SDKs and also readd FrozenWorld from Nuget to make it compile and build)

### Tried Unity Versions: 
- Unity 2020.3.24f1 - our setup
- Unity 2020.3.8f1 - sample project

### WLT,MRTK,ASA
using the latest version - our setup
Provided version - sample project

### XR Provider
both scenario - used WindowsMR / Windows Mixed Reality

### Hololens version 
![image](https://user-images.githubusercontent.com/17298033/165497314-2fa38620-9666-41a3-8118-9ba92db79eec.png)

Briefly:
Both projects and setup gave the same error and issues. WLT + ASA not working in both scenarios.

**Comment by fast-slow-still** [comment]
Great info, thanks! Could you attach your UnityPlayer.log file? Also, could you post what versions the various dependencies you are using?

* ASA
* WLT
* AR Foundation
* Which XR Plugin (OpenXR or WinMR) and what version

It sounds like ASA isn't successfully initializing, the problem may be buried in the [UnityPlayer.log](https://docs.microsoft.com/en-us/mixed-reality/world-locking-tools/documentation/howtos/contributing#log-files-from-the-device) file.

> The sample project had the same result (also worth mentioning that the sample project did not work out of the box, but we had to add the ASA core and ASA windows SDKs and also readd FrozenWorld from Nuget to make it compile and build)

Yes, that's correct. For legal reasons WLT can't distribute other products like ASA, but can only tell you how to add dependencies in the documentation, for example [here](https://microsoft.github.io/MixedReality-WorldLockingTools-Samples/Advanced/ASA/ASA.html#setup-and-tested-versions).

**Comment by Ahim13** [comment]
Sure. Attached the Player log
[UnityPlayer.log](https://github.com/microsoft/MixedReality-WorldLockingTools-Unity/files/8572391/UnityPlayer.log)

The versions are the following:

Our setup:
- ASA - 2.12.0
- WLT - 1.5.8
- AR Foundation - 4.0.12
- Windows XR Plugin - 4.6.1

Sample project (from the previous link):
- ASA - 2.12.0
- WLT - provided / not changed
- AR Foundation - provided / not changed (4.0.12)
- WinMR version - provided / not changed (4.4.2)

### Relevant packages in our setup:
![image](https://user-images.githubusercontent.com/17298033/165530104-31f1a173-b65a-4c1d-bba6-ebd03faf11b8.png)
![image](https://user-images.githubusercontent.com/17298033/165530142-bec0d350-8fc0-4b8b-a8c6-3bc991fa45e5.png)
![image](https://user-images.githubusercontent.com/17298033/165530190-255efd4d-259a-4d80-9c76-3b6f2ef16e9c.png)

**Comment by fast-slow-still** [comment]
I was able to repro the issue on a clean version of the sample.

Then I updated the AR Foundation package to version 4.1.9, and everything started working again.

Could you try updating AR Foundation and let me know if it fixes things or if you still have problems?

I'm going to leave this issue open to track updating the sample's AR Foundation package to 4.1.9 (I know 4.1.8 also works).

Thanks!

**Comment by Ahim13** [comment]
I can confirm, updating AR Foundation to 4.1.9 did the trick and solved it, now it is working.

Thanks!

**Comment by fast-slow-still** [comment]
Excellent, thanks for the feedback!
