### ISSUE TITLE
Please add video showing Space Pins and Ray Pins in use

### ISSUE THREAD

**Issue by REscanDon** [microsoft/MixedReality-WorldLockingTools-Unity#35]

**Comment by fast-slow-still** [comment]
I've produced a video for the Ray Pins sample (~5 minutes, 42MB). I'm currently waiting on hosting.

**Comment by fast-slow-still** [comment]
It has been a bit of a struggle getting videos hosted. This video was made February 23, 2020, and has only recently been posted.
https://channel9.msdn.com/Shows/Docs-Mixed-Reality/World-Locking-Tools-for-Unity
However, we are working to smooth the process. I have two more videos in the pipeline for hosting, and hope it might go more quickly in the future.
Thanks again for the excellent suggestion.
By the way, if you have video making suggestions after watching this one, or suggestions regarding video hosting or anything else related, I would be more than interested in your comments. Thanks!
