### ISSUE TITLE
Locked SpacePin position drifts over time when moving between floors in a building

### ISSUE THREAD

**Issue by BattleWorm** [microsoft/MixedReality-WorldLockingTools-Unity#65]
I've noticed that when using several SpacePins on different floors in a building, the far SpacePin (on a different floor than where the user is located) drifts over time (time frame: about 10 minutes). 

In my scenario, I'm trying to determine the geometry of a staircase using HoloLens 2. To do this, I'm setting measurement points on each floor and the edge of each step; I do this from about an arm's length away.
The workflow is basically the following:

* Start the app. The app sets up an AlignSubtree with two SpacePinOrientables. The hierarchy then looks like this:

![SpacePin_Hierarchy](https://user-images.githubusercontent.com/1758939/86350611-409c7100-bc63-11ea-819a-fe95360a4566.png)

* Enter the actual height between both floors in the app (measured beforehand using a laser ruler)
* Perform a thorough spatial scan of the entire staircase (WLT sets up a network of anchors along the staircase while doing this; all are in the same Fragment)
* Set a reference point on the bottom landing as a sibling of the SpacePins. 
  * Set the bottom SpacePin's position to that of the reference point, with Y set to 0. ResetModelingPose.
  * Set the bottom SpacePin's frozen pose to that of the reference point.
* Go to the upper landing, add a second reference point there as a sibling of the SpacePins.
  * Set the upper SpacePin's position to that of the reference point, with Y set to the measured height. ResetModelingPose.
  * Set the upper SpacePin's frozen pose to that of the reference point.
* Go back to the bottom landing. Measure each step of the staircase, bottom to top. Each measurement object is set as a sibling of the SpacePins.

Result: When arriving at the upper landing with the step measurements, the upper SpacePin has drifted down by several centimeters.

I'm using a custom TriangulatorY for interpolation between the two SpacePins on just the Y axis. 
I'll send the code your way directly via e-mail, together with a few photos of the staircase, the Unity log and Frozen World log.

Unity version: 2019.3.7f1
MRTK version: 2.4
WLT version: 0.8.5
Frozen World Engine version: 0.5.3
Device: HoloLens 2
OS version: 19041.1106.arm64fre.vb_release_svc_sydney_rel_prod.200605-1330
VS version: 2019 (16.6.2)
App build: Release, ARM64

**Comment by fast-slow-still** [comment]
Received all material, excellent bug report, your thoroughness is much appreciated. I will post back here after I have a chance to triage (probably this weekend). Thanks!

**Comment by fast-slow-still** [comment]
Sounds like we resolved this offline. Feel free to reopen if you think there's still a general issue here, or open a new issue if there's still something related which isn't working as expected.

A related issue that came up in offline discussions, starting off with WorldLocking disabled doesn't seem to actually start disabled, has been opened as separate issue #66 .
