### ISSUE TITLE
Need documentation and sample of how to best integrate with Azure Spatial Anchors

### ISSUE THREAD

**Issue by KevinKennedy** [microsoft/MixedReality-WorldLockingTools-Unity#83]
Scenarios:
- How do you place a Hologram in the world locked space that's really backed by an Azure Spatial Anchor.  Is this just attachment points?
- How to have the internal anchors used to manage the world locked space be backed by ASA.  This would let other HoloLenses participate in a shared experience in the world locked space
- Probably other scenarios

**Comment by fast-slow-still** [comment]
These aren't scenarios currently supported by WLT, nor anticipated to be supported by WLT. WLT uses local WorldAnchors (and in the upcoming XR SDK version XR Anchors). ASA aren't really appropriate for backing the WLT's spatialization.
